version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  reservations:
    build: 
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/reservations/.env
  
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:debug auth
    ports:
      - 3001:3001
      - 9229:9229
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/auth/.env
